{% set name = "shellcheck" %}
{% set version = "0.8.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz  # [not linux]
    sha256: dad3a2140389f5032996e6d381a47074ddbad6e5d9155f72ef732952c8861a3b  # [not linux]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.x86_64.tar.xz  # [linux64]
    sha256: ab6ee1b178f014d1b86d1e24da20d1139656c8b0ed34d2867fbb834dad02bf0a  # [linux64]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.aarch64.tar.xz  # [aarch64]
    sha256: 9f47bbff5624babfa712eb9d64ece14c6c46327122d0c54983f627ae3a30a4ac  # [aarch64]

build:
  number: 0

  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack                     # [not linux]
    - {{ native }}binutils

  host:
    - gmp  # [osx]

  run:
    - gmp  # [osx]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # [not linux]
  license_file: LICENSE.txt  # [linux]
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
